//
//  BeerListPresenter.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BeerListPresenter {

    // MARK: - Private properties -

    private unowned let view: BeerListViewInterface
    private let interactor: BeerListInteractorInterface
    private let wireframe: BeerListWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: BeerListViewInterface,
        interactor: BeerListInteractorInterface,
        wireframe: BeerListWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension BeerListPresenter: BeerListPresenterInterface {
}
