//
//  BeerListInteractor.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BeerListInteractor {
}

// MARK: - Extensions -

extension BeerListInteractor: BeerListInteractorInterface {
}
