//
//  BeerListInterfaces.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol BeerListWireframeInterface: WireframeInterface {
}

protocol BeerListViewInterface: ViewInterface {
}

protocol BeerListPresenterInterface: PresenterInterface {
}

protocol BeerListInteractorInterface: InteractorInterface {
}
