//
//  BeerListInterfaces.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol BeerListWireframeInterface: WireframeInterface {
    func presentBeerDetailWithData(data: BeerEntity)
}

protocol BeerListViewInterface: ViewInterface {
    func initializeBeerData(withData data: [BeerEntity])
    func appendBeerData(withData data: [BeerEntity])
    func animateActivityIndicator()
}

protocol BeerListPresenterInterface: PresenterInterface {
    func onViewDidAppear()
    func onSearchTextUpdated(text: String)
    func rowSelectedWithData(data: BeerEntity)
    func onTableViewNearingEnd()
}

protocol BeerListInteractorInterface: InteractorInterface {
    func getBeers(success: @escaping ([BeerEntity]) -> (), failure: @escaping (Error) -> ())
    func getBeers(withParameters parameters: [String: String], success: @escaping ([BeerEntity]) -> (), failure: @escaping (Error) -> ())
}
