//
//  BeerDetailViewController.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BeerDetailViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var descriptionText: UITextView!
    @IBOutlet weak var firstBrewedLabel: UILabel!
    @IBOutlet weak var abvLabel: UILabel!

    // MARK: - Public properties -

    var presenter: BeerDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.onViewDidLoad()
    }

    @IBAction func onBackPressed(_ sender: Any) {
        dismiss(animated: true)
    }

}

// MARK: - Extensions -

extension BeerDetailViewController: BeerDetailViewInterface {
    func fillViewData(with beer: BeerEntity) {
        if let url = URL(string: beer.image_url ?? "") {
            imageView.load(url: url)
        }
        titleLabel.text = beer.name
        descriptionText.text = beer.description
        if let firstBrewed = beer.first_brewed {
            firstBrewedLabel.text = NSLocalizedString("first_brewed_label", comment: "First brewed") + firstBrewed
        }
        if let abv = beer.abv {
            abvLabel.text = NSLocalizedString("abv_label", comment: "ABV") + String(abv)
        }
    }
    
}
