//
//  BeerDetailInterfaces.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol BeerDetailWireframeInterface: WireframeInterface {
}

protocol BeerDetailViewInterface: ViewInterface {
    func fillViewData(with beer: BeerEntity)
}

protocol BeerDetailPresenterInterface: PresenterInterface {
    func onViewDidLoad()
}

protocol BeerDetailInteractorInterface: InteractorInterface {
}
