//
//  BeerDetailPresenter.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BeerDetailPresenter {

    // MARK: - Private properties -

    private unowned let view: BeerDetailViewInterface
    private let interactor: BeerDetailInteractorInterface
    private let wireframe: BeerDetailWireframeInterface
    private let beerData: BeerEntity

    // MARK: - Lifecycle -

    init(
        view: BeerDetailViewInterface,
        interactor: BeerDetailInteractorInterface,
        wireframe: BeerDetailWireframeInterface,
        beerData: BeerEntity
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.beerData = beerData
    }
}

// MARK: - Extensions -

extension BeerDetailPresenter: BeerDetailPresenterInterface {
    func onViewDidLoad() {
        view.fillViewData(with: beerData)
    }
    
}
