//
//  BeerDetailWireframe.swift
//  BeerList
//
//  Created by Roberto Herranz on 21/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BeerDetailWireframe: BaseWireframe<BeerDetailViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "BeerDetail", bundle: nil)

    // MARK: - Module setup -

    init(beerData: BeerEntity) {
        let moduleViewController = storyboard.instantiateViewController(ofType: BeerDetailViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = BeerDetailInteractor()
        let presenter = BeerDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, beerData: beerData)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension BeerDetailWireframe: BeerDetailWireframeInterface {
}
